runtime: java
threadsafe: false
env: flex

handlers:
  - url: /.*
    script: this field is required, but ignored

readiness_check:
  path: "/index.html"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 500

runtime_config:  # Optional
  jdk: openjdk8
  server: jetty9